# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.ipynb"
      - "baseline/**"
      - "tests/**"
      - "results/**"
      - ".github/workflows/python-app.yml"
      - "requirements.txt"
      - "**.py"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-mpl nbval jupyter ipykernel matplotlib numpy Pillow
        # Project deps from requirements.txt (if present)
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # If your project is a package:
        if [ -f setup.py ] || [ -f pyproject.toml ]; then pip install -e.; fi

    - name: Quick sanity check
      run: |
        python -c "import sys; print('Python:', sys.version)"
        python -c "import matplotlib; print('Matplotlib:', matplotlib.__version__)"
        python -c "import nbval, jupyter, ipykernel; print('nbval/jupyter/ipykernel OK')"

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run image comparison tests
      env:
        MPLBACKEND: Agg    # ensures headless Matplotlib works in CI
        IMG_TOL: "0.0"  # set tolerance for image comparison
        XY_ABS_TOL: "0.0"
        XY_REL_TOL: "0.0"
      run: |
        pytest -q -s tests/test_mage_compare.py
      
